### ISSUE TITLE
Teacher Review for Week 4

### ISSUE THREAD

**Issue by leahsaph123** [leahsaph123/flask_portfolio#29]

**Comment by suneelanaidu** [comment]
Teacher's Review for week 4:
1. Good job and great team work.
2. Follow canvas requirements each week closely. 
3. Keep scrum board up-to-date, add new tasks as your PBL requires and move done items to Done column etc.
4.  Do collaborate more with other teams too. 
5. Your main web page must start looking like your own "unique idea" page and each About Us page can have more features/content added by the individual.
6. Continue Learning/Involvement in PBL and mini labs and it will help you for the final AP Test.
